In [7]:
# Import libraries
import pandas as pd
import sys
from sqlalchemy import create_engine, MetaData, Table, select, engine
import pyodbc

In [4]:
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)

Python version 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]
Pandas version 0.16.2

In [13]:
# Parameters
server = '192.168.1.52'
db = 'naturex'

# Create the connection
conn = pyodbc.connect('DRIVER={SQL Server};SERVER=' + DB['servername'] + ';DATABASE=' + DB['database'] + ';Trusted_Connection=yes')

# query db
sql = """

SELECT top 5 *
FROM dbo.raw_base_0217

"""
df = pandas.io.sql.read_sql(sql, conn)
df.head()

,Customer Type,Customer Distribution Channel,Customer Distribution Sub-channel,Customer Group Or Name,Customer Name,Customer Code,Ship To Country,Ship to State,Ship To City,Ship To Zip Code,...,Sales Agreement Currency,Sales Agreement Incoterm Name,Sales Agreement Country Zone,Sales Agreement Country Group,Sales Agreement Country Name,Company Code,Company Name,Invoice Incoterm,YearMonth,ID
0,Direct,Direct Customer,Customer,KERVAN GIDA SAN. VE TIC. A.S.,KERVAN GIDA SAN. VE TIC. A.S.,O411136,TURKEY,None,BEYLIKDUZU ISTANBUL,34524,...,EUR,EXW,EMEA,EUROPE (OTHER COUNTRIES),TURKEY,OO,Naturex Ltd,EXW,None,1
1,Direct,Direct Customer,Customer,R & R ICE CREAM (Leeming) UK LTD,R & R ICE CREAM (Leeming) UK LTD,O411026,U.K.,None,"NORTHALLERTON, North Yorkshire",DL7 9UL,...,GBP,DDP,EMEA,EUROPEAN UNION,U.K.,OO,Naturex Ltd,DDP,None,4
2,Direct,Direct Customer,Customer,R & R ICE CREAM (Leeming) UK LTD,R & R ICE CREAM (Leeming) UK LTD,O411026,U.K.,None,"NORTHALLERTON, North Yorkshire",DL7 9UL,...,GBP,DDP,EMEA,EUROPEAN UNION,U.K.,OO,Naturex Ltd,DDP,None,5
3,Direct,Direct Customer,Customer,R & R ICE CREAM (Leeming) UK LTD,R & R ICE CREAM (Leeming) UK LTD,O411026,U.K.,None,"NORTHALLERTON, North Yorkshire",DL7 9UL,...,GBP,DDP,EMEA,EUROPEAN UNION,U.K.,OO,Naturex Ltd,DDP,None,6
4,Direct,Direct Customer,Customer,R & R ICE CREAM (Leeming) UK LTD,R & R ICE CREAM (Leeming) UK LTD,O411026,U.K.,None,"NORTHALLERTON, North Yorkshire",DL7 9UL,...,GBP,DDP,EMEA,EUROPEAN UNION,U.K.,OO,Naturex Ltd,DDP,None,8

In [12]:
df.dtypes

Customer Type                              object
Customer Distribution Channel              object
Customer Distribution Sub-channel          object
Customer Group Or Name                     object
Customer Name                              object
Customer Code                              object
Ship To Country                            object
Ship to State                              object
Ship To City                               object
Ship To Zip Code                           object
Ship To Address Line 1                     object
Ship To Address Line 2                     object
Ship To Code                               object
Customer Bussiness Unit                    object
Customer Activity 1                        object
Customer Activity 2                        object
Customer Status                            object
Invoice Date Name                          object
Invoice Date                               object
Invoice Code                               object
Invoice Line Number                       float64
Product Business Unit Name                 object
Product Effective Product Line             object
Product Effective Product Line Name        object
Product Effective Product Subline Name     object
Product Common Name                        object
Product Form Name                          object
Product Name                               object
Product Ref                                object
Master Ref# Name                           object
                                           ...
Quantity                                  float64
Sales In USD                              float64
Sales In EUR                              float64
Current Margin In EUR                     float64
Current Margin In USD                     float64
Historical Margin In EUR                  float64
Historical Margin In USD                  float64
Current Unit Cost In EUR                  float64
Historical Unit Cost In EUR               float64
Current Unit Cost In USD                  float64
Historical Unit Cost In USD               float64
Unit Price In USD                         float64
Unit Price In EUR                         float64
Unit Price In Transactionnal Currency     float64
Sales In TCY                              float64
Transactional Currency                     object
Local Currency                             object
Sales Agreement                           float64
Sales Agreement EXW                       float64
Sales Agreement Transport                 float64
Sales Agreement Currency                   object
Sales Agreement Incoterm Name              object
Sales Agreement Country Zone               object
Sales Agreement Country Group              object
Sales Agreement Country Name               object
Company Code                               object
Company Name                               object
Invoice Incoterm                           object
YearMonth                                  object
ID                                          int64
dtype: object